version: '3'

services:
  # FastAPI application
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: glm-fast-api:1.0
    container_name: fastapi-app-v2
    ports:
      - "1313:80"  # Adjust the port as needed
    environment:
      - UVICORN_CMD="uvicorn main:app --host 0.0.0.0 --port 80 --reload"