version: '3'

services:
  # FastAPI application
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1313:80"  # Adjust the port as needed
    environment:
      - UVICORN_CMD="uvicorn main:app --host 0.0.0.0 --port 80 --reload"

  # Gunicorn server (optional, for production)
  gunicorn:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    depends_on:
      - fastapi
    ports:
      - "8001:80"  # Adjust the port as needed
    command: ["gunicorn", "main:app", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:80", "--reload"]

  # Nginx server (optional, for production)
  nginx:
    image: nginx:latest
    depends_on:
      - gunicorn
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - gunicorn
